sudo: required
services:
  - docker

before_install:
  - docker build -t vipinjain/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true vipinjain/react-test npm test

after_success:
  - docker build -t vipinjain/multi-client ./client
  - docker build -t vipinjain/multi-nginx ./nginx
  - docker build -t vipinjain/multi-server ./server
  - docker build -t vipinjain/multi-worker ./worker
  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push vipinjain/multi-client
  - docker push vipinjain/multi-nginx
  - docker push vipinjain/multi-server
  - docker push vipinjain/multi-worker


deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env:  MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-773329543652
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY